name: py37
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7.15
  - pip:
    - astropy==4.3.1
    - ipykernel==5.3.4
    - ipython==7.9.0
    - jupyter-client==6.1.12
    - matplotlib==3.2.2
    - matplotlib-inline==0.1.6
    - notebook==5.5.0
    - numpy==1.21.6
    - pandas==1.3.5
    - photutils==1.3.0
    - scipy==1.7.3
    - ccdproc==2.3.1
